[parity]
chain = "chain-spec.json"
base_path = "single-node"

[network]
port = 30301

[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[ui]
port = 8181

[dapps]
port = 8081

[ipc]
disable = true

[account]
password = ["../node.pwds"]
