[parity]
chain = "chain-spec.json"
base_path = "node1"

[network]
port = 30301

[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[ui]
port = 8181

[dapps]
port = 8081

[ipc]
disable = true

[account]
password = ["passwords"]

[mining]
engine_signer = "0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2"
reseal_on_txs = "none"
usd_per_tx = "0"
force_sealing = true

