[parity]
chain = "chain-spec.json"
base_path = "node2"

[network]
port = 30302

[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[ui]
port = 8182

[dapps]
port = 8082

[ipc]
disable = true

[account]
password = ["node.pwds"]

[mining]
engine_signer = "0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2"
reseal_on_txs = "none"
usd_per_tx = "0"
