[parity]
chain = "ouroboros-demo-spec.json"
base_path = "/tmp/parity0"

[network]
port = 30301

[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[ui]
port = 8181

[dapps]
port = 8081

[account]
password = ["node.pwds"]

[mining]
engine_signer = "0x00bd138abd70e2f00903268f3db08f2d25677c9e"
reseal_on_txs = "none"
usd_per_tx = "0"
